services:
  mongodb:
    image: mongo:4.4.2
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles
  app:
    image: crud-mongo
	environment:
     - spring.data.mongodb.host=172.17.0.1
    ports:
    - 8081:8081
    links:
    - mongodb